import type { ProTeamProfile } from '../types/analytics'

// NOTE: All stat benchmarks are coaching community estimates from film analysis.
// The NXL does not publish official per-point stats like survival % or OTB %.

export const PRO_TEAMS: ProTeamProfile[] = [
  {
    id: 'dynasty',
    name: 'San Diego Dynasty',
    tier: 'S',
    color: '#eab308',
    description: 'Co-founded by Ryan Greenspan, Alex Fraige, and Yosh Rau. 60+ pro major event wins — the winningest professional paintball team in history.',
    facts: [
      'Co-founded when JT USA executive Chuck Hendsch offered KAPP Factory members a pro contract (2001)',
      '60+ pro major event 1st place finishes',
      'Marcello Margott described as "arguably the best player in the world" by NXL preview',
      'Six longest tenured members: Fraige, Greenspan, Rau, Lang, Yarber, Margott',
    ],
    roster: ['Greenspan', 'Fraige', 'Rau', 'Margott', 'Montemayor', 'Schehr', 'Yarber', 'Frye', 'Barry'],
    benchmarks: { survivalPct: 75, otbPct: 90, killsPerPoint: 1.2, breakoutKills: 0.4, commsAvg: 4.5, disciplineScore: 90 },
    winPct: 72,
    survivalPct: 75,
    otbPct: 90,
    killsPP: 1.2,
    g1PP: 0.4,
    penPM: 0.3,
    avgComm: 4.5,
  },
  {
    id: 'damage',
    name: 'Tampa Bay Damage',
    tier: 'S',
    color: '#ef4444',
    description: 'Won the 2023 NXL Windy City Major and the 2025 NXL World Cup. Known for aggressive mid-game pushes and adaptive play-calling.',
    facts: [
      '2023 Windy City Major champions — their second win of that year',
      '2025 NXL World Cup champions',
      'Aggressive mid-game push style forces opponents into reactive positions',
    ],
    roster: ['Musser', 'Slowiak', 'Bouchez', 'Smith', 'Berger'],
    benchmarks: { survivalPct: 70, otbPct: 88, killsPerPoint: 1.3, breakoutKills: 0.45, commsAvg: 4.3, disciplineScore: 85 },
    winPct: 68,
    survivalPct: 70,
    otbPct: 88,
    killsPP: 1.3,
    g1PP: 0.45,
    penPM: 0.5,
    avgComm: 4.3,
  },
  {
    id: 'heat',
    name: 'Houston Heat',
    tier: 'A',
    color: '#f97316',
    description: 'Consistent A-tier performers known for disciplined lane control and aggressive doritto-side play.',
    facts: [
      'Known for developing strong rookie talent into pro-level players',
      'Emphasis on lane discipline and cross-field communication',
    ],
    roster: ['Hamil', 'Bernstein', 'Sullivan', 'Paxson', 'Grayson'],
    benchmarks: { survivalPct: 65, otbPct: 85, killsPerPoint: 1.0, breakoutKills: 0.35, commsAvg: 4.0, disciplineScore: 88 },
    winPct: 58,
    survivalPct: 65,
    otbPct: 85,
    killsPP: 1.0,
    g1PP: 0.35,
    penPM: 0.4,
    avgComm: 4.0,
  },
  {
    id: 'impact',
    name: 'Edmonton Impact',
    tier: 'A',
    color: '#3b82f6',
    description: 'Physical, aggressive play style. Known for strong breakout execution and tight snake-side control.',
    facts: [
      'Consistently competitive in NXL pro division',
      'Physical play style emphasizes body positioning and bunker control',
    ],
    roster: ['Telford', 'Richter', 'Paige', 'Silverman', 'Yachimec'],
    benchmarks: { survivalPct: 63, otbPct: 83, killsPerPoint: 1.1, breakoutKills: 0.38, commsAvg: 3.8, disciplineScore: 80 },
    winPct: 55,
    survivalPct: 63,
    otbPct: 83,
    killsPP: 1.1,
    g1PP: 0.38,
    penPM: 0.6,
    avgComm: 3.8,
  },
  {
    id: 'diesel',
    name: 'ac Diesel',
    tier: 'A',
    color: '#8b5cf6',
    description: 'Rose through off-season rankings with additions of Goldman, Rabackoff, and Spicka. Kyle Spicka co-hosts the Spick & Span show with Ryan Greenspan.',
    facts: [
      'Formerly styled as "ac:Diesel"',
      'Kyle Spicka career: pro debut 2010 with Ironmen, then Dynasty, Impact, Saints, ac Diesel',
      'Spicka co-hosts Spick & Span podcast with Ryan Greenspan',
    ],
    roster: ['Spicka', 'Goldman', 'Rabackoff', 'Trager', 'Bortko'],
    benchmarks: { survivalPct: 60, otbPct: 82, killsPerPoint: 0.95, breakoutKills: 0.32, commsAvg: 3.7, disciplineScore: 82 },
    winPct: 52,
    survivalPct: 60,
    otbPct: 82,
    killsPP: 0.95,
    g1PP: 0.32,
    penPM: 0.5,
    avgComm: 3.7,
  },
  {
    id: 'd3d4',
    name: 'D3-D4 Average',
    tier: 'Baseline',
    color: '#64748b',
    description: 'Average statistics for divisional (D3-D4) teams. Use as a baseline to measure your progress toward pro-level play.',
    facts: [
      'Represents the average competitive paintball player',
      'Good baseline for teams working toward semi-pro level',
    ],
    roster: [],
    benchmarks: { survivalPct: 45, otbPct: 70, killsPerPoint: 0.6, breakoutKills: 0.2, commsAvg: 2.8, disciplineScore: 65 },
    winPct: 45,
    survivalPct: 45,
    otbPct: 70,
    killsPP: 0.6,
    g1PP: 0.2,
    penPM: 1.2,
    avgComm: 2.8,
  },
]
